### ISSUE TITLE
`find-up` not found in 3.1.1 in the ESM build

### ISSUE THREAD

**Issue by elado** [Septh/rollup-plugin-node-externals#13]
Looks like 3.1.1 ESM build is broken: `find-up` moved to be a devDep and therefore, not found in runtime.

https://unpkg.com/browse/rollup-plugin-node-externals@3.1.1/dist/esm/index.js

```js
import { findUp } from 'find-up';
```

It could either move back to deps or not be an [`external`](https://github.com/Septh/rollup-plugin-node-externals/blob/5690c59f507c0936b3c46748fe99c6b8cfc056c6/rollup.config.mjs#L73) in the ESM build

**Comment by PabloSzx** [comment]
this needs to be fixed @Septh

**Comment by Septh** [comment]
Fixed in 3.1.2 😬
