### ISSUE TITLE
Doesn't work on Node 12

### ISSUE THREAD

**Issue by milesj** [Septh/rollup-plugin-node-externals#14]
After the v3 changes, this library no longer works on Node 12 since `??` isn't down-leveled.

```
     /home/runner/work/packemon/packemon/node_modules/rollup-plugin-node-externals/dist/cjs/index.js:315
                const pkg = JSON.parse((await fs.promises.readFile(packagePath)).toString()) ?? {};
                                                                                              ^

    SyntaxError: Unexpected token '?'
```

**Comment by Septh** [comment]
This is correct, and the `engines` field in package.json reflects this:

```json
  "engines": {
    "node": ">=14.0.0"
  }
```

Node 12 will be considered dead on [2020-04-30](https://nodejs.org/en/about/releases/). I'm just a little ahead of time :)

Can't you upgrade to Node 14?

**Comment by milesj** [comment]
Dropping it wasn't mentioned in the changelog, so was reporting it.

If it's intended that's fine. We support everything that is on LTS.

**Comment by Septh** [comment]
You're absolutely right, I'll update the docs. Leaving this issue open as a reminder.

Thanks.
