### ISSUE TITLE
is `rollup` supposed to be listed under `engines`?

### ISSUE THREAD

**Issue by jimmy-guzman** [Septh/rollup-plugin-node-externals#15]
Looks like [`rollup` is under `engines`](https://github.com/Septh/rollup-plugin-node-externals/blame/master/package.json#L33) in version `4.0.0`, is that expected?

I'm getting warnings in a few projects

```zsh
yarn install v1.22.17
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning rollup-plugin-node-externals@4.0.0: The engine "rollup" appears to be invalid.
```

**Comment by Septh** [comment]
Expected? Yes. Wrong? Indeed. :)

Thanks for reporting, will fix in next release. 

Leaving this issue open as a reminder.
