### ISSUE TITLE
Support rollup v3

### ISSUE THREAD

**Issue by nicolas377** [Septh/rollup-plugin-node-externals#16]
Rollup v3 has just been released, with a few breaking changes for plugins. This plugin is currently (5.0.0) not compatible with rollup v3. I'm happy to pr in changes if needed, but is a maintainer able to do that?

**Comment by Septh** [comment]
I'll be having a look into it very shortly. Thanks for noticing.

**Comment by Septh** [comment]
So, AFAIK the only issue is the plugin having a peer dependency on Rollup 2. Did you find anything else?

**Comment by nicolas377** [comment]
In all of my use cases, there aren't any runtime issues when using rollup 3, just the peer dep. Could you put up a PR for testing, just in case?

**Comment by Septh** [comment]
Since the plugin doesn't use any of the changed APIs in Rollup 3, I think it is best to release the fix right now as there are people waiting for it.

Please give v.5.0.1 a try and feel free to open a new issue if necessary. Thanx.
