### ISSUE TITLE
if use rollup-plugin-postcss some pkg not bundled in

### ISSUE THREAD

**Issue by panghaoyuan** [Septh/rollup-plugin-node-externals#18]
## description
I use `rollup-plugin-postcss` pkg in rollup.config.js
when i run `rollup --config rollup.config.js` 

in `index.scss.js`
```
import styleInject from '../../node_modules/style-inject/dist/style-inject.es.js';

var css_248z = ".masonry-absolute-wrap {\n  position: relative;\n}\n\n.masonry-absolute-item {\n  position: absolute;\n}";
styleInject(css_248z);

export { css_248z as default };
```

`style-inject` is not bundled in

## try
i set externals, but it;s still not bundled in
```
externals({
  deps: true,                 // Deps are external
  exclude: 'style-inject'  // Yet we want `electron-reload` bundled in
})
```

## example
https://github.com/jiaozitang/react-masonry-component2

## help

how can i do something to resolve this question

**Comment by Septh** [comment]
Did you try a regex rather than a string ?

```js 
externals({
  exclude: /style-inject/
})
```

**Comment by panghaoyuan** [comment]
> Did you try a regex rather than a string ?
> 
> ```js
> externals({
>   exclude: /style-inject/
> })
> ```

i set this， it has no effect
```
externals({
   exclude: [/style-inject/, /styleInject/, /^style-inject/, /^styleInject/]
})

```

**Comment by Septh** [comment]
Right, I got it: that's because you set `preserveModules` to true in `rollup.config.js`.

Remove this option, or set it to false, and everything is bundled as expected.

![image](https://user-images.githubusercontent.com/11949623/208798355-f926c644-bc5c-4f6f-987c-d9302c56ee6f.png)
![image](https://user-images.githubusercontent.com/11949623/208798846-7e61f2a9-9582-41dd-8f80-bdc9095f69ae.png)

**Comment by panghaoyuan** [comment]
@Septh 
yes，this can resolve this question。
but，i will get a big  bundle。
all component buddle in a `index.js` file。

My original idea was to get an on-demand loading component that could use ESM.
like this 
![4207ab34fb4e8e07c0b47ef9c552943](https://user-images.githubusercontent.com/28645409/208811807-7d698444-6d74-43ad-8882-2e02b5fdc1bf.jpg)

i see rollup‘s issue alread resolve `preserveModules option generate node_modules folder`，

https://github.com/rollup/rollup/issues/3684

Hope I can give you some help and help me solve this problem
