### ISSUE TITLE
some question about 'include' vs 'exclude'

### ISSUE THREAD

**Issue by huoyingyangjie** [Septh/rollup-plugin-node-externals#19]
Hi, i have a trouble in 'include' and 'exclude'.Now there are two external packages('axios' and 'core-js'), i only want extern axios. So i have below config and it can meet the needs.
```
externals({
            deps: false,
            include: ["axios"],       
        }),
```
But i use another config and it don't work.
```
externals({
            deps: true,
            exclude: ["core-js"],  
        }),
```
I don't know why, can you help me?

**Comment by Septh** [comment]
I'm not sure I'm getting the exact issue here. Could you please post your `package.json`'s `dependencies` and `devDependencies`?
