### ISSUE TITLE
Allow disabling node builtins handling entirely

### ISSUE THREAD

**Issue by segevfiner** [Septh/rollup-plugin-node-externals#21]
Currently there is no way to disable the handling of node builtins it will always either strip or add the `node:` prefix, its useful to be able to disable it so it can be handled by other plugins or configuration instead.

**Comment by Septh** [comment]
Hi! Do you mean you would like the `builtinsPrefix` setting taking a third option, say `ignore`? I'm not sure I can see the use for it. Could you please elaborate?

**Comment by segevfiner** [comment]
Having aliases set up for the node builtins, or a different plugin to polyfill them, so I'd rather they just be kept as is.

**Comment by Septh** [comment]
Fixed in 5.1.3. Enjoy! :)
