### ISSUE TITLE
feature: externalize imports from the same package

### ISSUE THREAD

**Issue by michaelfaith** [Septh/rollup-plugin-node-externals#23]
Overall, really liking this library.  The one feature that I wish it had was that it automatically externalized imports from the same package I'm building.  A common pattern for packages with secondary entrypoints is to use file-relative paths for imports you want in the same bundle, but package-relative paths for imports from other entry points (which should be externalized).

E.g. 
```typescript
// Should not be externalized
import Button from './Button';

// Should be externalized (since my package.name is '@my/components')
import Select from '@my/components/Select';
```

I would have expected that to be the default behavior, but if it makes more sense to have it as an opt-in thing, whatever you think is best.

**Comment by Septh** [comment]
Apologies for the late answer. 

If I understand correctly, it seems to me that what you're asking here should to be the responsibility of [@rollup/plugin-node-resolve](https://github.com/rollup/plugins/tree/master/packages/node-resolve).

**Comment by Septh** [comment]
I see your point. I have to give it some thinking. I'll let you know.

**Comment by Septh** [comment]
I'm sorry if I sound disappointing but I don't think I'm going to implement this - this is too much trouble for a not-so-frequent use case that has a simple solution.

I'm closing this issue, but feel free to comment again if needed.

**Comment by michaelfaith** [comment]
Thanks for giving it some consideration.  I disagree with it being categorized as an infrequent use case.  I think larger projects that have multiple entry points would consider this to be critical.  But I do respect the decision, and the workaround, as you point out, is fairly simple without it being built-in.

**Comment by Septh** [comment]
> I think larger projects that have multiple entry points would consider this to be critical.

To be fair, I'm not used to projects that large so I'll take your words on this. 🙂
