### ISSUE TITLE
Question about  dev dependencies.

### ISSUE THREAD

**Issue by icy0307** [Septh/rollup-plugin-node-externals#26]
Nice Work!
To be clear, this is a question no a bug.
In the `readme`,
you said 
> This will bundle your devDependencies in while leaving your dependencies, peerDependencies and optionalDependencies external.
So the default value of `devDeps` is true.
My question is that what is the scenario that someone wants to ship their library with dev dependencies bundled?

**Comment by Septh** [comment]
Actually, the default value of `devDeps` is `false` - i.e., development dependencies are *not* external. Only `deps`, `peerDeps` and `optDeps` have a default value of `true` - i.e., these dependencies are external. I double checked the README, this exactly is what is stated. 🙂

The scenario is, that when someone install your library as part of their project, npm will also install your lib's `dependencies` (and probably peers and maybe optionals). Those are required to make the library work on the user's computer.

On the other hand, `devDependecies` are dependencies that you, the author, need to build the library. Your user do not need them.

This scenario is the standard behavior of npm and this is what the default settings for this plugin support.

**Comment by Septh** [comment]
> Most of di library need `reflect-metadata` or something else to polyfill metadata api. But NOT list is as a dependency, but a [dev depdency](https://github.com/inversify/InversifyJS/blob/master/package.json)

[reflect-metada's readme](https://github.com/rbuckton/reflect-metadata#installation) instructs to install the package as a `dependency`. I'm not sure why InversifyJS use it as a `devDependency`, maybe they have a build step of some kind?

**Comment by icy0307** [comment]
@Septh  
I think it is only an old mistake to avoid  []non-singleton problem(https://github.com/inversify/InversifyJS/issues/1139)
It probably should list is as a dependency like `core-js`, after all , it is only a form of polyfill.
But again ,  maybe change the default behavior of dev dependency is better? it is quite hard to find a situation that library need bundle dev dependency and not to treat it as external.

**Comment by Septh** [comment]
> it is quite hard to find a situation that library need bundle dev dependency and not to treat it as external.

On the contrary, this is the typical case. If your code `import`s or `require`s a `devDependency`, then this dep *has* to be bundled in by Rollup otherwise the imported code won't be available to your user at runtime. Makes perfect sense.

**Comment by renyuneyun** [comment]
Great discussion...
To test my understanding: this plugin will not bundle a `devDependency` if it is not `import`-ed or `require`-ed, right? Therefore, tools such as `typescript` will not be bundled, even though listed as `devDependency`.

**Comment by Septh** [comment]
You're correct.
