### ISSUE TITLE
Not working with vite?

### ISSUE THREAD

**Issue by renyuneyun** [Septh/rollup-plugin-node-externals#28]
Hi. Thanks for the plugin.
I'm trying to make use of it, but it does not seem to work for [my project](https://github.com/renyuneyun/solid-helper) -- resulting file is still very large, containing the dependencies. To the contrary, another similar (yet less powerful) plugin [rollup-plugin-peer-deps-external](https://github.com/pmowrer/rollup-plugin-peer-deps-external) seems to work.

I'm using Vite 4.4.6, and configured the plugin like this:

```
export default defineConfig({
  build: {
    ...
    rollupOptions: {
      ...
      plugins: [
        nodeExternals(),
      ]
    },
  },
});
```

I saw #17, which has a different location to set this up. Also #17 appeared not to be resolved in the end. So I'm not sure how much I can learn from that -- I tried putting `nodeExternals()` to there but that did not seem to make any difference.

**Comment by Septh** [comment]
The plugin follows [Vite's compatibiliy guide](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility) and I know for a fact (because I used it in a Vite project) that it works with Vite 🤔.

`dependencies` are external by default, as well as `peerDependencies`. Are you sure you're not talking of `devDependencies`?

**Comment by renyuneyun** [comment]
Ok, it seems to work if I do the following:
```
export default defineConfig({
  build: {
    plugins: [
      { ...nodeExternals(), enforce: "pre" },
      ..
    ]
    ...
  },
});
```

The `enforce: "pre"` seems to be essential.

But still don't understand why...

**Comment by Septh** [comment]
> The `enforce: "pre"` seems to be essential.

This is a Vite-only feature that ensures this plugins runs before the others.

**Comment by Septh** [comment]
Version 7.1, released today, add official support for Vite without the above weird syntax. Enjoy!

**Comment by renyuneyun** [comment]
Great! Thanks for that!
