### ISSUE TITLE
2.1.1 .d.ts file isn't up-to-date

### ISSUE THREAD

**Issue by elado** [Septh/rollup-plugin-node-externals#3]
https://unpkg.com/browse/rollup-plugin-node-externals@2.1.1/dist/index.d.ts
doesn't contain `packagePath` option.

code is up to date though
https://unpkg.com/browse/rollup-plugin-node-externals@2.1.1/dist/es/index.js

**Comment by Septh** [comment]
Hmmm, looks like I ran the build script instead of dist :/

Fixed in 2.1.2. Thanks for reporting.
