### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length'), error when using with vitest 

### ISSUE THREAD

**Issue by chandu** [Septh/rollup-plugin-node-externals#30]
Hi,
Thanks for this plugin.
I have been using this in one of my projects without any issuess untill recent past with vitest/vite.

However I have upgraded the plguin version from 7.0.1 to 7.1.1 and since then when I run the `vitest run` or `vitest`, I am getting the error `TypeError: Cannot read properties of undefined (reading 'length'),` (thrown in the `resolveId` call)  and the process is exiting.

The same code is working fine with v 7.0.1 of this plugin.
I think the introduction of the `'order': 'pre'` of the `resolveId` function could be triggering this. https://github.com/Septh/rollup-plugin-node-externals/blob/main/source/index.ts#L231

Stackblitz with v7.0.1 works fine: https://stackblitz.com/edit/vitest-dev-vitest-ydhtdg?file=package.json

Stackblitz with v7.1.1 fails: https://stackblitz.com/edit/vitest-dev-vitest-jlcazj?file=package.json

**Comment by Septh** [comment]
That's odd. I'm going to investigate this.
Thanks for reporting!

**Comment by Septh** [comment]
So it seems that vitest calls the `resolvedId` hook before the `buildStart` hook, resulting in the `include` and `exclude` arrays being used before they are initialized.

I'm not sure whether this is vitest or vite misbehaving but this is clearly a bug on one of these tools. I'll need to further investigate and file an issue in the relevant repo.

Meanwhile, I just published version 7.1.2 that has a workaround for this.

Thanks again.

**Comment by Septh** [comment]
Turns out the Vitest team is already aware of the problem 🙂
* vitest-dev/vitest#5616
* vitest-dev/vitest#5479

**Comment by chandu** [comment]
Thanks for the prompt help.
I should have searched better for the error before filing this issue.
