### ISSUE TITLE
Support multiple package.json files

### ISSUE THREAD

**Issue by dbismut** [Septh/rollup-plugin-node-externals#6]
Hi thanks for this package!

I was about to post this issue in `rollup-plugin-auto-external` but this one seems to be more active!

I might be working on an edge case but in a monorepo a package can share dependencies and have some of its own.

Could it be possible that the `packagePath` support an array of paths?
If you're ok, I can make a PR for it.

**Comment by Septh** [comment]
By all means. The more use cases this package covers, the happier I am. 😉

**Comment by TomerAberbach** [comment]
For anyone thinking of implementing this, you could use [`find-up`](https://github.com/sindresorhus/find-up) with `'.git'` as an argument to find the root git directory (if one exists), and then repeatedly call [`read-pkg-up`](https://github.com/sindresorhus/read-pkg-up) to find `package.json` files until either the root git directory is reached or until no other `package.json` can be found.

**Comment by TomerAberbach** [comment]
@Septh I was considering working on this (unless @dbismut still wants to tackle it), and I had a question.

If I implemented this, then I think I'd want to add some tests, but I see you're not currently using any testing framework. Would you prefer I use any particular testing framework? I usually use [ava](https://github.com/avajs/ava) for my projects, but let me know if you prefer some other one.

Thanks in advance!

**Comment by dbismut** [comment]
Hey @TomerAberbach please go ahead! In the meantime I had to move to Webpack (don’t ask me why) and I have a very limited experience with bundlers, I’m sure you would do a better job ;)

**Comment by Septh** [comment]
@TomerAberbach > Agreed. Proper testing would definitely be a good thing to add to the project. TBH, I have no expertise at all in this area so my opinion as to which framework to use would be irrelevant - I think I'll just defer to your knowledge and wisdom here :)

**Comment by TomerAberbach** [comment]
Haha, sounds good!

I'll probably make a pull request just for setting up testing, and then follow up with another pull request for this feature + its tests (to keep the pull requests self-contained).

Would you want to add linting as well? Or maybe just add some basic automatic code formatting tool like [`prettier`](https://prettier.io)? (Would definitely understand not wanting to add a linter because they can be overbearing sometimes.)

**Comment by Septh** [comment]
Well, I think linting is great for large, multi-party projects but I'm really not sure about the benefits for a program this small. I'm afraid the ratio benefits/pain-you-know-where isn't good enough. 🙂

**Comment by TomerAberbach** [comment]
Fair enough. Will work on a pull request for multiple package.json files soon
